// Mock Data for 做饭灵感 App

export const mockIngredients = [
  "鸡蛋",
  "番茄",
  "米饭",
  "葱",
  "蒜",
  "盐",
  "油",
  "生抽",
  "青菜",
  "豆腐",
]

export const mockRecipes = [
  {
    id: "1",
    title: "番茄炒蛋",
    coverImage: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    cookingTime: 15,
    cookingMethod: "炒",
    tags: ["家常菜", "快手"],
    availableIngredients: ["鸡蛋", "番茄", "葱", "盐", "油"],
    missingIngredients: [],
    isAllAvailable: true,
  },
  {
    id: "2",
    title: "蒜蓉青菜",
    coverImage: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop",
    cookingTime: 10,
    cookingMethod: "炒",
    tags: ["素菜", "健康"],
    availableIngredients: ["青菜", "蒜", "盐", "油"],
    missingIngredients: [],
    isAllAvailable: true,
  },
  {
    id: "3",
    title: "麻婆豆腐",
    coverImage: "https://images.unsplash.com/photo-1582452932307-f63b7acc463e?w=400&h=300&fit=crop",
    cookingTime: 20,
    cookingMethod: "炒",
    tags: ["川菜", "下饭"],
    availableIngredients: ["豆腐", "葱", "盐"],
    missingIngredients: ["肉末", "豆瓣酱", "花椒"],
    isAllAvailable: false,
  },
  {
    id: "4",
    title: "蛋炒饭",
    coverImage: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop",
    cookingTime: 10,
    cookingMethod: "炒",
    tags: ["主食", "快手"],
    availableIngredients: ["鸡蛋", "米饭", "葱", "盐", "油"],
    missingIngredients: [],
    isAllAvailable: true,
  },
  {
    id: "5",
    title: "红烧肉",
    coverImage: "https://images.unsplash.com/photo-1623653387945-2fd25214f8fc?w=400&h=300&fit=crop",
    cookingTime: 60,
    cookingMethod: "煮",
    tags: ["硬菜", "下饭"],
    availableIngredients: [],
    missingIngredients: ["五花肉", "冰糖", "生抽", "老抽", "八角"],
    isAllAvailable: false,
  },
]

export const mockRecipeDetail = {
  id: "1",
  title: "番茄炒蛋",
  coverImage: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=400&fit=crop",
  cookingTime: 15,
  cookingMethod: "炒",
  tags: ["家常菜", "快手", "下饭"],
  availableIngredients: [
    { name: "鸡蛋", amount: "2个" },
    { name: "番茄", amount: "1个" },
    { name: "葱", amount: "适量" },
    { name: "盐", amount: "少许" },
    { name: "油", amount: "适量" },
  ],
  missingIngredients: [
    { name: "糖", amount: "少许" },
  ],
  steps: [
    { order: 1, description: "番茄洗净切块，鸡蛋打散加少许盐搅拌均匀。" },
    { order: 2, description: "热锅凉油，倒入蛋液炒至凝固盛出备用。" },
    { order: 3, description: "锅中再加少许油，放入番茄块翻炒至软烂出汁。" },
    { order: 4, description: "加入炒好的鸡蛋，加盐调味，翻炒均匀即可出锅。" },
  ],
  tips: "番茄要炒出汁水才好吃，可以加少许糖中和酸味。",
}
