/**
 * 菜谱数据 - 与 /api/recommend 共享
 */

export interface Ingredient {
  name: string
  amount?: string
}

export interface Recipe {
  id: string
  title: string
  emoji?: string
  cookingTime: number
  cookingMethod: "炒" | "煮" | "蒸" | "烤" | "炸" | "凉拌" | "其他"
  tags: string[]
  mainIngredients: Ingredient[]
  seasonings: Ingredient[]
  steps?: { order: number; description: string }[]
  tips?: string
}

export const RECIPES: Recipe[] = [
  {
    id: "1",
    title: "番茄炒蛋",
    coverImage: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    cookingTime: 15,
    cookingMethod: "炒",
    tags: ["家常菜", "快手"],
    mainIngredients: [
      { name: "番茄", amount: "2个" },
      { name: "鸡蛋", amount: "3个" },
    ],
    seasonings: [
      { name: "葱", amount: "适量" },
      { name: "盐", amount: "少许" },
      { name: "油", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "番茄洗净切块，鸡蛋打散加少许盐搅匀" },
      { order: 2, description: "热锅凉油，倒入蛋液炒至凝固盛出" },
      { order: 3, description: "锅中再加少许油，放入番茄块翻炒出汁" },
      { order: 4, description: "加入炒好的鸡蛋，调入盐翻炒均匀即可" },
    ],
    tips: "番茄要炒出汁水才好吃，可以加少许糖提鲜",
  },
  {
    id: "2",
    title: "蒜蓉青菜",
    coverImage: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop",
    cookingTime: 10,
    cookingMethod: "炒",
    tags: ["素菜", "健康"],
    mainIngredients: [{ name: "青菜", amount: "300g" }],
    seasonings: [
      { name: "蒜", amount: "3瓣" },
      { name: "盐", amount: "适量" },
      { name: "油", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "青菜洗净沥干水分，蒜切末" },
      { order: 2, description: "热锅凉油，爆香蒜末" },
      { order: 3, description: "放入青菜大火快炒，加盐调味即可" },
    ],
    tips: "青菜要大火快炒，保持翠绿和脆嫩口感",
  },
  {
    id: "3",
    title: "麻婆豆腐",
    coverImage: "https://images.unsplash.com/photo-1582452932307-f63b7acc463e?w=400&h=300&fit=crop",
    cookingTime: 20,
    cookingMethod: "炒",
    tags: ["川菜", "下饭"],
    mainIngredients: [
      { name: "豆腐", amount: "1块" },
      { name: "肉末", amount: "100g" },
    ],
    seasonings: [
      { name: "豆瓣酱", amount: "1勺" },
      { name: "花椒", amount: "适量" },
      { name: "葱", amount: "适量" },
      { name: "姜", amount: "适量" },
      { name: "蒜", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "豆腐切小块，焯水后捞出备用" },
      { order: 2, description: "热锅凉油，下肉末炒散至变色" },
      { order: 3, description: "加入豆瓣酱、葱姜蒜末炒出红油" },
      { order: 4, description: "加入适量清水，放入豆腐块烧煮入味" },
      { order: 5, description: "水淀粉勾芡，撒花椒粉出锅" },
    ],
    tips: "豆腐提前焯水可以去除豆腥味",
  },
  {
    id: "4",
    title: "蛋炒饭",
    coverImage: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop",
    cookingTime: 10,
    cookingMethod: "炒",
    tags: ["主食", "快手"],
    mainIngredients: [
      { name: "米饭", amount: "1碗" },
      { name: "鸡蛋", amount: "2个" },
    ],
    seasonings: [
      { name: "葱", amount: "适量" },
      { name: "盐", amount: "适量" },
      { name: "油", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "鸡蛋打散，米饭提前打散备用" },
      { order: 2, description: "热锅宽油，倒入蛋液炒至半凝固" },
      { order: 3, description: "立即加入米饭翻炒，使蛋液包裹每粒米" },
      { order: 4, description: "加入葱花和盐调味，翻炒均匀即可" },
    ],
    tips: "用隔夜冷饭炒更容易粒粒分明",
  },
  {
    id: "5",
    title: "红烧肉",
    coverImage: "https://images.unsplash.com/photo-1623653387945-2fd25214f8fc?w=400&h=300&fit=crop",
    cookingTime: 60,
    cookingMethod: "煮",
    tags: ["硬菜", "下饭"],
    mainIngredients: [{ name: "五花肉", amount: "500g" }],
    seasonings: [
      { name: "冰糖", amount: "30g" },
      { name: "生抽", amount: "2勺" },
      { name: "老抽", amount: "1勺" },
      { name: "八角", amount: "2个" },
      { name: "桂皮", amount: "1小块" },
      { name: "葱", amount: "适量" },
      { name: "姜", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "五花肉切块，冷水下锅焯水去血沫" },
      { order: 2, description: "锅中放少许油，加入冰糖小火炒出糖色" },
      { order: 3, description: "放入五花肉块翻炒上色" },
      { order: 4, description: "加入生抽、老抽、八角、桂皮、葱姜和适量水" },
      { order: 5, description: "大火烧开后转小火炖煮1小时至肉酥烂" },
      { order: 6, description: "大火收汁即可出锅" },
    ],
    tips: "炒糖色时火候要小，颜色变成琥珀色时立刻下肉",
  },
  {
    id: "6",
    title: "可乐鸡翅",
    coverImage: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=400&h=300&fit=crop",
    cookingTime: 30,
    cookingMethod: "煮",
    tags: ["肉类", "下饭"],
    mainIngredients: [{ name: "鸡翅", amount: "8个" }],
    seasonings: [
      { name: "可乐", amount: "1罐" },
      { name: "生抽", amount: "2勺" },
      { name: "姜", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "鸡翅洗净，两面各划两刀方便入味" },
      { order: 2, description: "冷水下锅焯水，撇去浮沫后捞出" },
      { order: 3, description: "锅中放少许油，将鸡翅煎至两面金黄" },
      { order: 4, description: "加入可乐、生抽和姜片，大火烧开" },
      { order: 5, description: "转中小火煮20分钟，最后大火收汁" },
    ],
    tips: "可乐要用普通可乐，不要用零度可乐",
  },
  {
    id: "7",
    title: "酸辣土豆丝",
    coverImage: "https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=400&h=300&fit=crop",
    cookingTime: 15,
    cookingMethod: "炒",
    tags: ["川菜", "下饭"],
    mainIngredients: [{ name: "土豆", amount: "2个" }],
    seasonings: [
      { name: "干辣椒", amount: "5个" },
      { name: "醋", amount: "2勺" },
      { name: "盐", amount: "适量" },
      { name: "葱", amount: "适量" },
      { name: "蒜", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "土豆去皮切成细丝，用清水浸泡去除淀粉" },
      { order: 2, description: "热锅凉油，爆香干辣椒和蒜末" },
      { order: 3, description: "土豆丝沥干水分倒入锅中大火快炒" },
      { order: 4, description: "沿锅边烹入醋，加盐调味，撒葱花即可" },
    ],
    tips: "土豆丝泡水去淀粉后要充分沥干，否则炒时会粘锅",
  },
  {
    id: "8",
    title: "宫保鸡丁",
    coverImage: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=400&h=300&fit=crop",
    cookingTime: 25,
    cookingMethod: "炒",
    tags: ["川菜", "下饭"],
    mainIngredients: [
      { name: "鸡胸肉", amount: "200g" },
      { name: "花生", amount: "50g" },
    ],
    seasonings: [
      { name: "干辣椒", amount: "10个" },
      { name: "花椒", amount: "适量" },
      { name: "葱", amount: "适量" },
      { name: "姜", amount: "适量" },
      { name: "蒜", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "鸡胸肉切丁，用料酒和淀粉腌制15分钟" },
      { order: 2, description: "花生米提前用少许油炒香备用" },
      { order: 3, description: "调制宫保汁：生抽、醋、糖、淀粉、水拌匀" },
      { order: 4, description: "热锅宽油，滑炒鸡丁至变色盛出" },
      { order: 5, description: "爆香花椒、干辣椒、葱姜蒜，放回鸡丁" },
      { order: 6, description: "淋入宫保汁快速翻炒，出锅前加入花生米" },
    ],
    tips: "鸡丁腌制时加少许油可以防止粘连",
  },
  {
    id: "9",
    title: "清蒸鲈鱼",
    coverImage: "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=400&h=300&fit=crop",
    cookingTime: 20,
    cookingMethod: "蒸",
    tags: ["海鲜", "清淡"],
    mainIngredients: [{ name: "鲈鱼", amount: "1条" }],
    seasonings: [
      { name: "葱", amount: "适量" },
      { name: "姜", amount: "适量" },
      { name: "蒸鱼豉油", amount: "2勺" },
    ],
    steps: [
      { order: 1, description: "鲈鱼处理干净，两面各划三刀" },
      { order: 2, description: "鱼身抹少许料酒和盐，肚子里放姜片" },
      { order: 3, description: "水开后放入蒸锅，大火蒸8-10分钟" },
      { order: 4, description: "出锅后倒掉蒸出的水，撒上葱丝" },
      { order: 5, description: "淋上蒸鱼豉油，泼上热油即可" },
    ],
    tips: "蒸鱼时间要根据鱼的大小调整，不要蒸太久",
  },
  {
    id: "10",
    title: "蒜蓉生蚝",
    coverImage: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=400&h=300&fit=crop",
    cookingTime: 15,
    cookingMethod: "蒸",
    tags: ["海鲜"],
    mainIngredients: [{ name: "生蚝", amount: "6个" }],
    seasonings: [
      { name: "蒜", amount: "2头" },
      { name: "葱", amount: "适量" },
      { name: "盐", amount: "适量" },
      { name: "油", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "生蚝刷洗干净，撬开壳取出生蚝肉" },
      { order: 2, description: "蒜切末，葱切葱花" },
      { order: 3, description: "生蚝肉放回壳中，撒上蒜末和少许盐" },
      { order: 4, description: "水开后放入蒸锅，大火蒸5分钟" },
      { order: 5, description: "出锅撒葱花，淋上热油即可" },
    ],
    tips: "选择新鲜的生蚝，蒜末可以提前用油炒香",
  },
  {
    id: "11",
    title: "青椒肉丝",
    coverImage: "https://images.unsplash.com/photo-1595743825637-cdafc8ad4173?w=400&h=300&fit=crop",
    cookingTime: 20,
    cookingMethod: "炒",
    tags: ["家常菜", "下饭"],
    mainIngredients: [
      { name: "青椒", amount: "3个" },
      { name: "猪肉", amount: "200g" },
    ],
    seasonings: [
      { name: "盐", amount: "适量" },
      { name: "生抽", amount: "1勺" },
      { name: "淀粉", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "青椒切丝，猪肉切丝后用淀粉腌制" },
      { order: 2, description: "热锅宽油，先滑炒肉丝至变色盛出" },
      { order: 3, description: "锅中再加少许油，炒香后放入青椒丝" },
      { order: 4, description: "青椒炒至断生后放回肉丝" },
      { order: 5, description: "加生抽和盐调味，翻炒均匀即可" },
    ],
    tips: "肉丝提前腌制可以使其更嫩滑",
  },
  {
    id: "12",
    title: "番茄蛋汤",
    coverImage: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
    cookingTime: 15,
    cookingMethod: "煮",
    tags: ["汤类", "家常菜"],
    mainIngredients: [
      { name: "番茄", amount: "2个" },
      { name: "鸡蛋", amount: "2个" },
    ],
    seasonings: [
      { name: "葱", amount: "适量" },
      { name: "盐", amount: "适量" },
      { name: "水", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "番茄洗净切块，鸡蛋打散" },
      { order: 2, description: "锅中加水烧开，放入番茄块煮软" },
      { order: 3, description: "加入盐调味" },
      { order: 4, description: "蛋液慢慢淋入锅中形成蛋花" },
      { order: 5, description: "撒葱花出锅即可" },
    ],
    tips: "蛋液要最后放，形成漂亮的蛋花",
  },
  {
    id: "13",
    title: "凉拌黄瓜",
    coverImage: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop",
    cookingTime: 10,
    cookingMethod: "凉拌",
    tags: ["凉菜", "清爽"],
    mainIngredients: [{ name: "黄瓜", amount: "2根" }],
    seasonings: [
      { name: "蒜", amount: "3瓣" },
      { name: "醋", amount: "2勺" },
      { name: "盐", amount: "适量" },
      { name: "香油", amount: "少许" },
    ],
    steps: [
      { order: 1, description: "黄瓜洗净，用刀拍碎后切段" },
      { order: 2, description: "蒜切末放入碗中" },
      { order: 3, description: "加入醋、盐和香油调成凉拌汁" },
      { order: 4, description: "将凉拌汁倒入黄瓜中拌匀即可" },
    ],
    tips: "黄瓜拍碎比直接切更易入味",
  },
  {
    id: "14",
    title: "地三鲜",
    coverImage: "https://images.unsplash.com/photo-1601311830595-4f8e2b4a8a62?w=400&h=300&fit=crop",
    cookingTime: 25,
    cookingMethod: "炒",
    tags: ["素菜", "东北菜"],
    mainIngredients: [
      { name: "土豆", amount: "1个" },
      { name: "茄子", amount: "1个" },
      { name: "青椒", amount: "2个" },
    ],
    seasonings: [
      { name: "盐", amount: "适量" },
      { name: "生抽", amount: "1勺" },
      { name: "油", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "土豆、茄子切滚刀块，青椒切块" },
      { order: 2, description: "分别将土豆和茄子炸至金黄捞出" },
      { order: 3, description: "锅中留少许油，炒香后放入青椒块" },
      { order: 4, description: "放入炸好的土豆和茄子" },
      { order: 5, description: "加生抽和盐调味，翻炒均匀即可" },
    ],
    tips: "土豆和茄子炸过后更香，表皮会形成一层硬壳",
  },
  {
    id: "15",
    title: "干煸四季豆",
    coverImage: "https://images.unsplash.com/photo-1557844352-761f2565b576?w=400&h=300&fit=crop",
    cookingTime: 20,
    cookingMethod: "炒",
    tags: ["川菜", "下饭"],
    mainIngredients: [
      { name: "四季豆", amount: "300g" },
      { name: "肉末", amount: "100g" },
    ],
    seasonings: [
      { name: "干辣椒", amount: "5个" },
      { name: "花椒", amount: "适量" },
      { name: "盐", amount: "适量" },
      { name: "蒜", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "四季豆去头尾和老筋，掰成段" },
      { order: 2, description: "热锅宽油，放入四季豆炸至表皮起皱" },
      { order: 3, description: "捞出沥油备用" },
      { order: 4, description: "锅中留少许油，爆香干辣椒、花椒和蒜末" },
      { order: 5, description: "放入肉末炒散，加入四季豆翻炒" },
      { order: 6, description: "加盐调味即可出锅" },
    ],
    tips: "四季豆一定要炸熟，否则可能引起食物中毒",
  },
  {
    id: "16",
    title: "红烧茄子",
    coverImage: "https://images.unsplash.com/photo-1536304929831-ee1b51bd5bec?w=400&h=300&fit=crop",
    cookingTime: 20,
    cookingMethod: "煮",
    tags: ["家常菜", "下饭"],
    mainIngredients: [
      { name: "茄子", amount: "2个" },
      { name: "肉末", amount: "100g" },
    ],
    seasonings: [
      { name: "豆瓣酱", amount: "1勺" },
      { name: "葱", amount: "适量" },
      { name: "姜", amount: "适量" },
      { name: "蒜", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "茄子切条，用盐腌制10分钟后挤去水分" },
      { order: 2, description: "热锅宽油，将茄子炸至金黄捞出" },
      { order: 3, description: "锅中留少许油，炒香葱姜蒜和豆瓣酱" },
      { order: 4, description: "放入肉末炒散，加入茄子翻炒" },
      { order: 5, description: "加少许水和生抽，焖煮5分钟入味" },
    ],
    tips: "茄子用盐腌制后更易入味，且能减少用油量",
  },
  {
    id: "17",
    title: "糖醋里脊",
    coverImage: "https://images.unsplash.com/photo-1562967914-608f82629710?w=400&h=300&fit=crop",
    cookingTime: 30,
    cookingMethod: "炸",
    tags: ["鲁菜", "酸甜"],
    mainIngredients: [{ name: "里脊肉", amount: "300g" }],
    seasonings: [
      { name: "番茄酱", amount: "3勺" },
      { name: "糖", amount: "2勺" },
      { name: "醋", amount: "2勺" },
      { name: "淀粉", amount: "适量" },
      { name: "鸡蛋", amount: "1个" },
    ],
    steps: [
      { order: 1, description: "里脊肉切条，用料酒、盐和蛋清腌制" },
      { order: 2, description: "裹上淀粉，油温170度炸至金黄捞出" },
      { order: 3, description: "调制糖醋汁：番茄酱、糖、醋、淀粉、水拌匀" },
      { order: 4, description: "锅中放少许油，倒入糖醋汁烧开" },
      { order: 5, description: "放入炸好的里脊肉快速翻炒，裹匀糖醋汁即可" },
    ],
    tips: "里脊肉复炸一次会更酥脆",
  },
  {
    id: "18",
    title: "鱼香肉丝",
    coverImage: "https://images.unsplash.com/photo-1592303637753-ce1e5b5c42c2?w=400&h=300&fit=crop",
    cookingTime: 25,
    cookingMethod: "炒",
    tags: ["川菜", "下饭"],
    mainIngredients: [
      { name: "猪肉", amount: "200g" },
      { name: "木耳", amount: "50g" },
      { name: "胡萝卜", amount: "1根" },
      { name: "青椒", amount: "1个" },
    ],
    seasonings: [
      { name: "豆瓣酱", amount: "1勺" },
      { name: "醋", amount: "1勺" },
      { name: "糖", amount: "1勺" },
    ],
    steps: [
      { order: 1, description: "猪肉切丝，用料酒和淀粉腌制" },
      { order: 2, description: "木耳、胡萝卜、青椒切丝" },
      { order: 3, description: "调制鱼香汁：生抽、醋、糖、淀粉、水拌匀" },
      { order: 4, description: "热锅宽油，滑炒肉丝至变色盛出" },
      { order: 5, description: "爆香豆瓣酱，放入配菜丝翻炒" },
      { order: 6, description: "放回肉丝，淋入鱼香汁快速翻炒即可" },
    ],
    tips: "鱼香味的关键是糖、醋、豆瓣酱的比例",
  },
  {
    id: "19",
    title: "水煮牛肉",
    coverImage: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=400&h=300&fit=crop",
    cookingTime: 30,
    cookingMethod: "煮",
    tags: ["川菜", "辣"],
    mainIngredients: [
      { name: "牛肉", amount: "300g" },
      { name: "豆芽", amount: "200g" },
    ],
    seasonings: [
      { name: "干辣椒", amount: "10个" },
      { name: "花椒", amount: "适量" },
      { name: "豆瓣酱", amount: "2勺" },
      { name: "葱", amount: "适量" },
      { name: "姜", amount: "适量" },
      { name: "蒜", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "牛肉逆纹切薄片，用料酒和淀粉腌制" },
      { order: 2, description: "豆芽焯水铺在碗底" },
      { order: 3, description: "热锅宽油，爆香干辣椒、花椒、豆瓣酱、葱姜蒜" },
      { order: 4, description: "加入适量清水烧开" },
      { order: 5, description: "滑入牛肉片煮至变色，倒入铺好豆芽的碗中" },
      { order: 6, description: "撒上干辣椒碎和花椒，泼上热油即可" },
    ],
    tips: "牛肉切薄片并逆纹切会更嫩",
  },
  {
    id: "20",
    title: "蒜蓉西兰花",
    coverImage: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&h=300&fit=crop",
    cookingTime: 10,
    cookingMethod: "炒",
    tags: ["素菜", "健康"],
    mainIngredients: [{ name: "西兰花", amount: "1颗" }],
    seasonings: [
      { name: "蒜", amount: "5瓣" },
      { name: "盐", amount: "适量" },
      { name: "油", amount: "适量" },
    ],
    steps: [
      { order: 1, description: "西兰花掰成小朵，用淡盐水浸泡后洗净" },
      { order: 2, description: "西兰花焯水1分钟，捞出过凉水沥干" },
      { order: 3, description: "蒜切末" },
      { order: 4, description: "热锅凉油，爆香蒜末，放入西兰花快炒" },
      { order: 5, description: "加盐调味，翻炒均匀即可出锅" },
    ],
    tips: "西兰花焯水可以保持翠绿，且能缩短炒制时间",
  },
]

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id)
}

export function getRecipeByTitle(title: string): Recipe | undefined {
  return RECIPES.find((r) => r.title === title)
}
